### ISSUE TITLE
Can't develop run app because cant find .nuxt/tsconfig.json

### ISSUE THREAD

**Issue by lwjcjmx123** [trobonox/kanri#122]
in tsconfig.json its extends  ./.nuxt/tsconfig.json, but .nuxt is in gitignore, cant clone that directory
```json
{
  // https://v3.nuxtjs.org/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

**Comment by lwjcjmx123** [comment]
fixed with run  yarn nuxi typecheck

**Comment by trobonox** [comment]
Just a little heads up (even though it seems like you've managed to solve the issue yourself), the .nuxt folder with all needed components should be automatically generated as soon as you do yarn install and any nuxt command like yarn dev (which runs the nuxt dev server and the tauri dev mode)

**Comment by lwjcjmx123** [comment]
@trobonox thanks for that, I just clone the repo and open in vscode, vscode hint me that some ts error， I have no experience in nuxt, so I dont know it will generage automatically。I just follow the link of tsconfig.json https://v3.nuxtjs.org/concepts/typescript, then run the suggest command yarn nuxi typecheck, it's working for me
