### ISSUE TITLE
Delete confirmation when trying to delete a board or card in Kanban view

### ISSUE THREAD

**Issue by trobonox** [trobonox/kanri#218]
X icon on Kanban cards/columns should show a delete confirmation modal asking for a confirmation on this destructive action.
For power users, a double click could be a shortcut bypassing this confirmation.
The double click logic can be achieved with the ClickCounter component which is already used for the quick edit/modal open login inside the Kanban card component.

**Comment by hycday** [comment]
fully agree with this feature request and if i may add, same for column deletion (actually might be even more critical to avoid mistakes and delete many tasks at once)
