### ISSUE TITLE
feature request: show thumbnail view of board in the home view

### ISSUE THREAD

**Issue by retsyo** [trobonox/kanri#227]
as the title says. Thank you.

**Comment by trobonox** [comment]
Thanks for the feature request!

I'm afraid I don't fully understand what you would like to see. Currently the boards also show a "thumbnail" with a simplified representation of columns with cards inside.
Are you expecting a more detailed version of this, which is basically like a screenshot of the board/a full preview?

If you can explain your idea a bit more detailed I can give you some feedback if this is possible and something I can implement.

**Comment by retsyo** [comment]
Currently, 3 abstarct columns is shown
![now](https://github.com/trobonox/kanri/assets/7960913/b810def2-44d0-417f-9ca1-6afd97f786c1)

but it could be more meaningful if a snapshot of my board is used
![expected](https://github.com/trobonox/kanri/assets/7960913/1a374a5f-6a00-4a42-91d8-624dd296b16e)

**Comment by retsyo** [comment]
more accompanying issues:
1. if every snapshots of the board are saved as local image files, there could be too many small files. So maybe no file is used at all, only a thumbnail of the board is rendered
2. if the board is too wide/high, only parts of the board is allowed to be displayed in the thumbnail
3. we can set the size of thumbnail

**Comment by trobonox** [comment]
Thanks for clarifying, I'll try to see if I can just render more detailed columns in a preview without using images or too many resources.
Will add this to my todos (see projects tab here on GitHub) and work on it as soon as I have some time to do so.

**Comment by trobonox** [comment]
I have implemented new thumbnails with the latest release. Would you mind checking it out and letting me know if that's what you meant? If so, in later releases I will also add the possibility to further customize the previews.

**Comment by retsyo** [comment]
yes, it is what I mean. thanx
