### ISSUE TITLE
Feature Request: Provide homebrew package

### ISSUE THREAD

**Issue by BhaveshDiwan** [trobonox/kanri#273]
Most Macintosh users prefer [Homebrew](https://brew.sh/) to manage their software installations. 
It would be highly desirable to have Kanri available in the homebrew ecosystem.
The following documentation might be helpful in achieving this: https://docs.brew.sh/Formula-Cookbook

**Comment by trobonox** [comment]
Thank you very much for your feature request.
This is a great idea! I have recently switched to a Mac myself and I definitely see how this can be very useful.
Currently I am on vacation but when I'm back I will take a look and see if I can make Kanri available through homebrew.

If you have any other feature request or find any bug, feel free to open another issue.

**Comment by BhaveshDiwan** [comment]
Thanks @trobonox for making me feel welcome. I am great proponent of open source applications which support linux and mac, therefore have been using Kanri in my important day-to-day tasks and truly love your app.

I have been using it for some time now and have identified a lot of places where improvements will be welcome. If you like, I can start creating issues ranging from UI enhancements to feature requests, which I as an end user would be happy to see.

**Comment by trobonox** [comment]
Sure, it would be greatly appreciated if you could open a few issues so I can add some things to the roadmap.

**Comment by trobonox** [comment]
Done!
Here's the commands to install Kanri through homebrew:
```bash
brew tap trobonox/cask
brew install kanri
```

Will add this to the release notes so everyone can know that it's possible to install using homebrew.
I'll also look into the possibility of adding the project to the official homebrew packages so people can omit the `tap` command, but I think it needs a little user testing to make sure everything works fine before I attempt doing that.

**Comment by BhaveshDiwan** [comment]
@trobonox I check the installation with homebrew. Although it was able to download the package, however, the application failed to launch. My suspicion is that it downloaded package for wrong architecture (intel) as I am on M1 silicon. Upon manually downloading the package for right architecture from GH release, the applications works fine.

Suggestion `brew tap trobonox/kanri` seem to be a better choice.

<img width="372" alt="Screenshot 2023-08-30 at 00 49 33" src="https://github.com/trobonox/kanri/assets/9309009/49462130-c7f5-4805-8978-478faf6be250">

**Comment by BhaveshDiwan** [comment]
> Sure, it would be greatly appreciated if you could open a few issues so I can add some things to the roadmap.

@trobonox, I have been extensively using the app for a while now. I anticipate some free time after September 15. Will open a few enhancement requests after that.

**Comment by trobonox** [comment]
> @trobonox I check the installation with homebrew. Although it was able to download the package, however, the application failed to launch. My suspicion is that it downloaded package for wrong architecture (intel) as I am on M1 silicon. Upon manually downloading the package for right architecture from GH release, the applications works fine.
> 
> 
> 
> Suggestion `brew tap trobonox/kanri` seem to be a better choice.
> 
> 
> 
> <img width="372" alt="Screenshot 2023-08-30 at 00 49 33" src="https://github.com/trobonox/kanri/assets/9309009/49462130-c7f5-4805-8978-478faf6be250">
> 
> 

Thanks for the name suggestion, will probably change that.

Also the issue you are receiving is not because of a wrong architecture but rather because non-signed Apple Silicon executables built with Tauri throw that issue. It's a restriction from Apple and only signing the package would be a fix, which I belive I would need to pay for. A temporary workaround should be to use the `xattr -c Applications/kanri.app` command, which should fix the error (not sure about the path, make sure to double check that in Finder). This should also occur for the builds available on GitHub but maybe that was not the case for you since you had the application installed before.

**Comment by trobonox** [comment]
> I am aware of this certificate challenge with apple, however, this time I strongly think it is not that. With such situation the usual error dialog I see complaints about untrusted application and user is still able to launch it by allowing it from Gatekeeper under settings.
> 
> 
> 
> However, in this case the dialog box outright said "application is damaged and can't be opened".
> 
> 
> 
> Although, I am able to open a manually downloaded application by allowing in gatekeeper - so I do not think there is anything wrong with the application at all, but the architecture downloaded via homebrew was incorrect.

I have also seen the "application is damaged" error when using the releases from GitHub for the first time, but maybe you're right and the downloaded architecture is in fact incorrect. Unfortunately I'm not sure if I can do a lot about it, since I am using the method every other homebrew package does to resolve the architecture. Will double-check to make sure it's not a bug on my end though, so thanks for pointing it out.

**Comment by BhaveshDiwan** [comment]
Thanks @trobonox
I will also check on my part and update you here as soon as I can - Most likely I will be able to get time after 15 Sept.

**Comment by BhaveshDiwan** [comment]
@trobonox I was able to check the homebrew again. The architecture being download is correct. Unfortunately the application has stopped opening, perhaps because of mac update. I will create a separate issue soon.

As you suggested above the xattr command to run unsigned application, i think you should also include this in readme
`xattr -cr /Applications/kanri.app/`
