### ISSUE TITLE
Card tags

### ISSUE THREAD

**Issue by trobonox** [trobonox/kanri#297]
A way to tag cards without it producing too much visual clutter
This is something that needs to be figured out from both a design and UX perspective

**Comment by trobonox** [comment]
Hi, thanks for showing interest in contributing! Feel free to give it a try, I have assigned you to the issue. 
Keep in mind that this requires changes both to the EditCard modal for the input, the logic to save it from there (you can look at tasks etc. as a reference) and also a change to the Card component to display the tags. Moreover, you should add this new field in `utils/kanban-types.d.ts`. Generally, you can also reference how things like card tasks were implemented here.

If you have any questions on the codebase or need other help, feel free to ask, but I am not always available since I am currently quite busy with personal matters.
Thanks :)

**Comment by trobonox** [comment]
Another important thing:
If it's about any decision to make and you're not sure (especially related to how the details in the UI should work), feel free to ask ASAP to prevent doing unnecessary work

**Comment by Streissi** [comment]
thx for the information, first of all, i will take a look at the code base to check how the things are done in there.

**Comment by trobonox** [comment]
Any updates? Feel free to let me know if you're stuck on anything or need some help to understand the code.

**Comment by Streissi** [comment]
I have started to implement the tags and have no problems understanding the code, but I may need help when I am further along with the work

**Comment by trobonox** [comment]
> I have started to implement the tags and have no problems understanding the code, but I may need help when I am further along with the work 
> 
> But now I'm on vacation so the work will be a bit delayed

No worries, thanks for the status update and enjoy your vacation!
Feel free to reach out if you have any questions and I'll try my best to help out.

**Comment by Streissi** [comment]
hi,

i want to understand how the modal dialogs work, but it is hard for me to figure it out. Can you help me with this topic?

**Comment by trobonox** [comment]
And just as a side note, if you'd like to chat outside of just the GitHub issue, feel free to add me on Discord (@trobo.tech) or write me an email (hello@trobo.tech) if any of these means of communication are easier for you :)

**Comment by Streissi** [comment]
i send a friend request on discord, i'm tiranius :)
