### ISSUE TITLE
Background image appears again

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#312]
When a background image is set, you can delete it with "Reset Background Image".
But when leaving the board (back button) and opening that board again, the image is still there.

This even happens when you choose an image, do NOT press 'save background setting' but immediately reset it. 
Nevertheless the image is saved and will be shown after closing/opening the board.

**Comment by trobonox** [comment]
Thanks for reporting this. Will try to reproduce and fix this.

**Comment by trobonox** [comment]
Fixed, will come with the next release.
