### ISSUE TITLE
Missing 'close' or 'back' in Settings menu and in Import/Export menu

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#314]
While the help menu has an X to close it (ESC works as well)

the 'Settings' and the 'Import/Export' don't have an X, neither does ESC work.
You'll have to press either 'Home' or can use 'ALT + left' which is not intuitive. ESC would be preferred.
Other way could be to show the "back" arrow at the left side as is shown when you've opened a board.

**Comment by trobonox** [comment]
That makes sense, will add the back arrow, thanks.

**Comment by trobonox** [comment]
Added the back arrows, this will also drop with the next release.

**Comment by trobonox** [comment]
Out with the new release
