### ISSUE TITLE
Window size reset when starting kanri

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#319]
The last size of the window isn't saved.
When starting kanri it starts with a predefined size (don't know the reason for this size).

Even the start-up option 'start maximised' is ignored by kanri.

kanri_0.5.0_x64_en-US.msi

**Comment by trobonox** [comment]
This is something I don't really have control over, since it's mostly dictated by Tauri settings. I can try to see if there's any way to change this behaviour to what you expect, but no guarantees that I can figure it out.

**Comment by trobonox** [comment]
There is a Tauri plugin to enable this behaviour, but from my testing it is buggy and slows down app loads, which is something I don't want. This feature will be on an indefinite hold until the plugin works well enough for me.

**Comment by trobonox** [comment]
Should be fixed, see #533
