### ISSUE TITLE
Feature Request: Creation of (empty/default) boards

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#320]
When adding a board some default columns and cards are added.

This should be selectable in 'Create a new board' popup, perhaps checkboxes for 'create default columns' and 'create example cards'.
Selection of those checkboxes should be saved for next board creation.

Also the default columns could be user definable. 

Even better way would be to create one's preferred layout and being able to copy this user defined board (no copy board feature yet, I think).

**Comment by trobonox** [comment]
Thanks for your request. It is in my roadmap/todos to allow a customized creation of boards, most notably allowing you to either use the default board template which is used now or customize your columns as you please.

**Comment by trobonox** [comment]
You now have more granular options to edit the boards you create. You can toggle the old behaviour or change the columns (and even delete all of them if you'd like to) directly from the popup to create a board.
