### ISSUE TITLE
Request for FAQ, manual or help

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#323]
I've found the double-click trick by accident in the release notes.

> Confirmation for deleting columns and cards (bypass using double-click)

As the functionality grows it's probably helpful to create a manual or update the 'help' regularly to have a collection of those tricks.
(I would never have figured this out, as no hint is shown when hovering the 'x' either.)

**Comment by trobonox** [comment]
Thanks for your request, it is my intention to document all of these "hidden" features in the new documentation at kanriapp.com, I just had no time so far due to personal reasons.
