### ISSUE TITLE
Unable to delete task if there's a long string without spaces inside

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#324]
I've copied a task into kanri which included a very long link.

The task is shown now in 3 lines where the middle line has the 'x' for deleting at the right side.

If the link is not too long you can reach the x but the second task in this example seems to be impossible to delete?
![grafik](https://github.com/trobonox/kanri/assets/25332701/0e1ec251-6bc7-4f9f-8e98-4a1bd5f238ce)

**Comment by PeterP2** [comment]
Maybe it's because of the custom display scaling settings on Windows 10, set to 125% (which is not very unusual on laptops I think).

**Comment by trobonox** [comment]
Thanks for pointing this out. WIll look into it and see if I can reproduce and fix the issue.

**Comment by trobonox** [comment]
Fixed, the fix will be out with the next release.
