### ISSUE TITLE
Installation: Problem creating shortcut link

### ISSUE THREAD

**Issue by PeterP2** [trobonox/kanri#330]
I think I've seen this already once (not on reinstallation) when installing kanri_0.5.0_x64_en-US.msi.
Now shown while installing kanri_0.5.1_x64_en-US.msi.

It successfully created a shortcut on the desktop and updated the shortcut in Start menu, so not sure where else it tries to create another link?
Which folder should I check for access?

![grafik](https://github.com/trobonox/kanri/assets/25332701/ed572870-90f3-450c-aefb-1af939d4f6f2)

**Comment by trobonox** [comment]
This is a strange issue. Never encountered this before.
If both the Desktop and Start menu shortcuts are working, there is nothing to worry about I'd say. You can investigate on your own but again the installation is a standard Tauri procedure so probably not a lot I can influence here.

**Comment by PeterP2** [comment]
https://github.com/tauri-apps/tauri/issues/4237

**Comment by PeterP2** [comment]
'Destination' does not mean the folder where the shortcut will be saved, but the kanri folder itself (c:\program files\kanri).

Uninstalled kanri, created \kanri manually (owner = myself), deleted \kanri, installed again (owner of \kanri = System) but no error now?

Closing for now...
