### ISSUE TITLE
Boards With Different Names but the Same ID Cannot Be Open Simultaneously

### ISSUE THREAD

**Issue by immijimmi** [trobonox/kanri#365]
After creating a template board and exporting it into multiple projects, I'm unable to have 2 of these boards open in Kanri at the same time.
The boards have each been renamed and so do not have matching names any longer, but retain matching IDs in the JSON. Attempting to import 2 of these boards back into Kanri results in attempting to overwrite the first board with the second.

Although I'm aware that logically it does not make sense to manage two boards simultaneously which have the same identifier attached to them, the process of exporting/importing data causes duplication of IDs in boards which may then become forked. It would be good to have a way to resolve that without manually editing the JSON.

**Comment by immijimmi** [comment]
Possible solutions:
- When exporting a board, provide an option to "export from template", setting a new name and generating a new ID in the exported JSON
- Add a "duplicate board" button which creates a new board in Kanri and assigns a fresh name & ID to the duplicate
- When attempting to import a board with a duplicate ID, provide an option to import the board as a new board and set a fresh ID and name

**Comment by immijimmi** [comment]
Note - When attempting to import a board with a duplicate ID, the confirmation dialog indicates that <board name> already exists, implying that this is due to a duplicated name. However, multiple boards with the same name may co-exist in Kanri provided that they have different IDs. It may be worth rewording this dialog to indicate that the issue is specifically importing a board with the same ID as an existing board.

**Comment by trobonox** [comment]
Thank you for pointing this out. I understand your concerns and appreciate that you provided some solutions. Will have a look and see what I think works best. It will probably be a combination of the "duplicate board" feature and some edits in the dialog to have better wording and potentially provide more options when importing.

**Comment by trobonox** [comment]
Fixed with the latest release
