### ISSUE TITLE
Consider making it remember window position and size (or if it was maximized too)

### ISSUE THREAD

**Issue by TsukiZero** [trobonox/kanri#533]
The application opens up just a little bit bit bigger than my screen (probably +100 pixels in height and width, even after shrinking it in a previous session. Might be useful to have it remember the previous size.

**Comment by trobonox** [comment]
Remembering the size has been suggested and I definitely want to add this. It will have to wait a bit though, because I ran into some issues with the Tauri plugin that handles window positions and sizes.

**Comment by trobonox** [comment]
Update: this should work now (at least on Windows). On macOS there might still be some issues when maximizing, so if enough people are bothered by the issue I might have to revert this change.

**Comment by TsukiZero** [comment]
Thank you so much!
