### ISSUE TITLE
Cannot full import from Kanri export

### ISSUE THREAD

**Issue by Auerilas** [trobonox/kanri#535]
Hi,
I'm using Kanri on two different devices, and what I'm trying to do is export Kanri to my dropbox, then import it on the second device when I start up. However, when I try to 'full import', I get the error:

"Could not load JSON file. Please check file is formatted correctly and not from an older version of Kanri"

However, I CAN import individual boards successfully.

Here is the full export JSON that doesn't work:

`{
  "activeTheme": "dark",
  "boardSortingOption": "default",
  "boards": [
    {
      "columns": [
        {
          "cards": [
            {
              "name": "Nate"
            }
          ],
          "id": "zzobb4ler3zxr993ex8lvtjf",
          "title": "Todo"
        },
        {
          "cards": [],
          "id": "ustn5ue81eeje1z9k6fkacgc",
          "title": "Work in progress"
        },
        {
          "cards": [],
          "id": "ycz0ye021lodtc04gkcrmeu0",
          "title": "Done"
        }
      ],
      "id": "vigw2l5qd6kwwiwmoynk52ua",
      "lastEdited": "2024-03-27T11:21:29.985Z",
      "title": "test"
    }
  ],
  "colors": {
    "accent": "#2150c0",
    "accentDarker": "#17367d",
    "bgPrimary": "#111112",
    "elevation1": "#1b1b1d",
    "elevation2": "#27272a",
    "elevation3": "#333338",
    "text": "#f4f4f5",
    "textButtons": "#f1f5f9",
    "textD1": "#e4e4e7",
    "textD2": "#d4d4d8",
    "textD3": "#a1a1aa",
    "textD4": "#71717a"
  },
  "columnZoomLevel": 0,
  "lastInstalledVersion": "0.6.1",
  "savedCustomTheme": null
}`

and here is the individual board that does work:

`{
  "columns": [
    {
      "cards": [
        {
          "name": "Nate",
          "id": "eogkje2ilkbovuyjcqxq1xpj"
        }
      ],
      "id": "zzobb4ler3zxr993ex8lvtjf",
      "title": "Todo"
    },
    {
      "cards": [],
      "id": "ustn5ue81eeje1z9k6fkacgc",
      "title": "Work in progress"
    },
    {
      "cards": [],
      "id": "ycz0ye021lodtc04gkcrmeu0",
      "title": "Done"
    }
  ],
  "id": "vigw2l5qd6kwwiwmoynk52ua",
  "lastEdited": "2024-03-27T11:25:38.231Z",
  "title": "test"
}`

Any help here would be appreciated.

**Comment by Auerilas** [comment]
I guess for clarity

Kanri -> Export full -> Import full NOT WORKING
Kanri -> Export single board -> Import single board WORKING

**Comment by trobonox** [comment]
Thanks for your bug report, I will take a look soon to see what's going on. Might be some oversight in the validation of JSON files for the full import.

**Comment by trobonox** [comment]
Found the issue - I wasn't handling optional values correctly, so the import threw an error. This is fixed and will be out with the next release.

**Comment by Auerilas** [comment]
Thank you!

**Comment by trobonox** [comment]
Just a little information: the next release will take a while to come out. If you want the issue to be resolved earlier, you can join the [official Discord server](https://discord.gg/J3TZzKAcCy) and download preview/beta builds (currently I have created some for Windows and Linux, but I can also make one for macOS if it's required)

**Comment by trobonox** [comment]
Fixed with release v0.7
