### ISSUE TITLE
Task checkbox gets messed

### ISSUE THREAD

**Issue by Sengflex** [trobonox/kanri#553]
Hi, I noticed this when adding a task: 
If the text for task is longer then the checkbox shape gets messed
I'm using the 0.7.0 version

1. Create a task for a card
2. Add a longer text description, like 139 chars long
3. See error. The checkbox gets smaller in width

Screenshots
![image](https://github.com/trobonox/kanri/assets/74029090/16009dba-5cbc-4d65-a93f-76409f4adb88)

Desktop
 - OS: Windows 11 and 10
 - Version 0.7.0

**Comment by trobonox** [comment]
Thanks for reporting this issue, I have found it myself while developing other features. It is already resolved and the fix will be out with the next release v0.7 which should come out in approximately 1-2 weeks.

**Comment by trobonox** [comment]
Fixed in v0.7, release is out now
