### ISSUE TITLE
[BUG] Can't move cards to blank columns

### ISSUE THREAD

**Issue by pnxl** [trobonox/kanri#57]
**Describe the bug**
If a column is blank, cards are unable to be moved there

**To Reproduce**
1. Create a new column
2. Make sure the column is blank
3. Attempt to move a card to that column

**Expected behavior**
for it to move lmao

**Desktop (please complete the following information):**
 - macOS Ventura 13.1
 - whatever the latest version of kanri is it doesnt actually show the version (hey that makes a good feature suggestion)

**Comment by pnxl** [comment]
if that wasnt clear enough heres a screen recording

https://user-images.githubusercontent.com/66474423/211159088-8bc650fd-a8b0-47b2-a15f-f1d4a712e20a.mov

**Comment by trobonox** [comment]
This seems to be an issue related to my drag and drop library's CSS not loading correctly. I thought I'd fixed this with the last release, could you reinstall maybe? If it's still broken, I'll send you a debug build later and then please send me some console output so I can see what's going on.

**Comment by pnxl** [comment]
![Screenshot 2023-01-08 at 01 38 42](https://user-images.githubusercontent.com/66474423/211165672-1643bdbd-63c9-4327-81de-0de73258b0f2.png)

solved
