### ISSUE TITLE
RPM release

### ISSUE THREAD

**Issue by skinatro** [trobonox/kanri#9]
Hello,

Thanks for making kanri,
Is there any way to make a rpm release alongside deb release.
I can test it out as well since I am on fedora 36

**Comment by trobonox** [comment]
Sorry for the delayed reply, for some reason I did not get a notification for this.

Currently Tauri does not seem to support making rpm packages, but I can try to see if I can find a workaround and do it manually until Tauri has official rpm and/or Flatpak support (both are planned).
I'll get back to you after I made some attempts.

**Comment by trobonox** [comment]
I have just added an RPM package, please let me know if it works!

**Comment by skinatro** [comment]
It works without any issues.
Thanks a lot, i will report if i find any bugs
